/* empty css                      */import{a as m,S as f,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const p="53445349-55a99b0310e27289c38888bf9",d="https://pixabay.com/api/";async function g(o){const r={key:p,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:50};return(await m.get(d,{params:r})).data}const c=document.getElementById("gallery"),u=document.getElementById("loader"),y=new f(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const r=o.map(e=>`
      <li class="gallery__item">
        <a class="gallery__link" href="${e.largeImageURL}">
          <img class="gallery__image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${e.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
        </div>
      </li>`).join("");c.insertAdjacentHTML("beforeend",r),y.refresh()}function b(){c.innerHTML=""}function L(){u.classList.add("is-visible")}function w(){u.classList.remove("is-visible")}const a=document.getElementById("search-form"),v=a.elements["search-text"];a.addEventListener("submit",E);function E(o){o.preventDefault();const r=v.value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search query",timeout:3e3});return}b(),L(),g(r).then(e=>{if(!e||!Array.isArray(e.hits)||e.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:4e3});return}h(e.hits),n.success({title:"Success",message:`Found ${e.totalHits} images`,timeout:2500})}).catch(e=>{console.error("Error fetching images:",e),n.error({title:"Error",message:"Something went wrong while fetching images.",timeout:3e3})}).finally(()=>{w()}),a.reset()}
//# sourceMappingURL=index.js.map
